# Site settings
url:                    "lifeflowercare.com"
language:               ""

## Page title tags are composed of the site.title and page.title
title:                  "Life Flower"

## Used in meta tags
description:            "Relieve, Repair, Relax."

instagram-url:          "http://www.instagram.com/lifeflowercare"

google-verification:    ""

# Handling Reading
include:
  - ".htaccess"
  - "_pages"

destination: docs

collections:
- products

exclude:
  - "/assets/"
  - "bower.json"
  - "composer.json"
  - "composer.lock"
  - "DOC.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "/gulp/"
  - "gulpfile.js"
  - "LICENSE.md"
  - "Makefile"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "rev-manifest.json"

# Plugins
gems:             ["jekyll-sitemap", "jekyll-paginate"]

# Conversion
incremental:      true

# Serving
# url:            ""
# baseurl:        "" # does not include hostname

# Outputting
permalink:        "/blog/:year/:title/"
paginate_path:    "/blog/page:num"
paginate:         5

compress_html:
  ignore:
    envs: [development]
